changes in conanfile.py for pkg version
elear-solutions/paho.mqtt.c pull request #4
Opened 2019-07-30 07:13 UTC by amiya-elear

2019-07-31 18:58 UTC, deekshith-elear approved these changes

2019-08-01 05:57 UTC, varun-elear requested changes

2019-08-01 05:57 UTC, varun-elear commented on conanfile.py
> +    description = "This recipe file used to build and package binaries of Pahomqtt repository"
`pahomqttc` instead of `Pahomqtt`

2019-08-01 06:03 UTC, varun-elear approved these changes

2019-08-01 06:03 UTC, amiya-elear commented on conanfile.py
> +    description = "This recipe file used to build and package binaries of Pahomqtt repository"
handled

2019-08-01 06:13 UTC, merged